git:
  quiet: true
  depth: 3

os: linux
dist: focal # Ubuntu 20.04
language: c
cache: ccache

#
# Try building on these architectures; all are 64-bit, and all but
# "s390x", a/k/a z/Architecture, are little-endian.
#

jobs:
  fast_finish: true
  include:
  - name: "ppc64le"
    arch: ppc64le
    if: branch != coverity_scan
  - name: "s390x"
    arch: s390x
    if: branch != coverity_scan
  allow_failures:
    - arch: ppc64le # Since 20 Feb 2021 often times out trying to boot.

env:
  global:
    - MAKEFLAGS='-j 2' # Travis CI VMs come with 2 cores

addons:
  apt:
    packages:
      - libdbus-1-dev
      - libbluetooth-dev
      - libnl-genl-3-dev
      - libibverbs-dev

script:
  - uname -a
  - date
  - apt list --installed 'lib*-dev'
  - ./build_matrix.sh
